---
- name: Install xorg
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-xprop
    - xorg-xmodmap
    - xorg-xrandr
    - xorg-xinit
    - xorg-xev
    - xorg-xset
    - xorg-xrdb
    - xorg-xbacklight
