export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="af-magic"
COMPLETION_WAITING_DOTS="true"

plugins=(git git-flow npm ssh-agent colorize colored-man composer extract zsh-syntax-highlighting node npm bundler docker fasd)

source $ZSH/oh-my-zsh.sh

export EDITOR="vim"
export PATH=/usr/local/bin:$PATH

alias dc=docker-compose
alias copy="xclip -selection c"

drm()  { docker rm $(docker ps -qa); }
drme() { docker rm $(docker ps -qa --filter 'status=exited'); }
dri()  { docker rmi $(docker images -q --filter "dangling=true"); }
dgo() { docker exec -ti $@ bash }
dip()  { docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$@"; }

dcrefresh() {
	dc stop $1 && dc rm -v -f $1 && dc up -d $1
}
