export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="af-magic"
COMPLETION_WAITING_DOTS="true"

plugins=(git git-flow npm ssh-agent colorize colored-man composer extract zsh-syntax-highlighting node npm bundler docker fasd)

source $ZSH/oh-my-zsh.sh

export EDITOR="vim"
export PATH=$HOME/.gem/ruby/2.2.0/bin:/usr/local/bin:$PATH
export PATH=$HOME/.gem/ruby/2.3.0/bin:/usr/local/bin:$PATH
export TERM="xterm"

alias dc=docker-compose
alias dcr="dc run --rm"
alias copy="xclip -selection c"
alias mysql="dcr db mysql"
alias 3mt="~/.screenlayout/3-monitors.sh"
alias 2mt="~/.screenlayout/2-monitors.sh"
alias 1mt="~/.screenlayout/1-monitor.sh"

drm()  { docker rm $(docker ps -qa); }
drme() { docker rm $(docker ps -qa --filter 'status=exited'); }
dri()  { docker rmi $(docker images -q --filter "dangling=true"); }
dgo() { docker exec -ti $@ bash }
dip()  { docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$@"; }

dcrefresh() {
	dc stop $1 && dc rm -v -f $1 && dc up -d $1
}
